// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ66DoLBzOrcexBCnUkP3atkBzdFhPWag',
    appId: '1:478284969407:web:7db14a8e83475e203e5d0a',
    messagingSenderId: '478284969407',
    projectId: 'rivilodriver',
    authDomain: 'rivilodriver.firebaseapp.com',
    storageBucket: 'rivilodriver.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MkKlP2Zs6wVnuk9Jn6O4YVYv1J2FAew',
    appId: '1:478284969407:android:4104b133bcf7f0de3e5d0a',
    messagingSenderId: '478284969407',
    projectId: 'rivilodriver',
    storageBucket: 'rivilodriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxRcWemCUHz1bV0NlShB34JuN2CThLfg',
    appId: '1:478284969407:ios:96bad994cbded2ba3e5d0a',
    messagingSenderId: '478284969407',
    projectId: 'rivilodriver',
    storageBucket: 'rivilodriver.firebasestorage.app',
    iosBundleId: 'com.eubalkans.rivilodriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbxRcWemCUHz1bV0NlShB34JuN2CThLfg',
    appId: '1:478284969407:ios:96bad994cbded2ba3e5d0a',
    messagingSenderId: '478284969407',
    projectId: 'rivilodriver',
    storageBucket: 'rivilodriver.firebasestorage.app',
    iosBundleId: 'com.eubalkans.rivilodriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ66DoLBzOrcexBCnUkP3atkBzdFhPWag',
    appId: '1:478284969407:web:dd92fd2b7dc8cda73e5d0a',
    messagingSenderId: '478284969407',
    projectId: 'rivilodriver',
    authDomain: 'rivilodriver.firebaseapp.com',
    storageBucket: 'rivilodriver.firebasestorage.app',
  );
}
